BEGIN
DECLARE
@NUNOTA INT

DECLARE cursor_ATUALIZAR_PEDIDO_OMNICHANNEL CURSOR FOR
SELECT TOP 100
       TGFCAB.NUNOTA
 FROM TGFCAB (NOLOCK)
 INNER JOIN USE_VENDA (NOLOCK) ON USE_VENDA.CHAVENFE = TGFCAB.CHAVENFE
 INNER JOIN USE_OMNICHANNEL (NOLOCK) ON USE_OMNICHANNEL.VENDALOJA = USE_VENDA.LOJA AND USE_OMNICHANNEL.VENDA = USE_VENDA.CODIGO
 AND TGFCAB.CODTIPOPER = 3289
 AND USE_OMNICHANNEL.NUMEROPEDIDOPLATAFORMA IS NOT NULL
 AND USE_OMNICHANNEL.SISTEMAORIGEM = 'Site'
 AND TGFCAB.NUMPEDIDO2 IS NULL
 WHERE TGFCAB.DTNEG >= CONVERT(DATE,'01/05/2023',103)

OPEN cursor_ATUALIZAR_PEDIDO_OMNICHANNEL


FETCH NEXT FROM cursor_ATUALIZAR_PEDIDO_OMNICHANNEL INTO @NUNOTA


WHILE @@FETCH_STATUS = 0
BEGIN


EXEC AD_ATUALIZAR_PEDIDO_OMNICHANNEL_USE @NUNOTA


FETCH NEXT FROM cursor_ATUALIZAR_PEDIDO_OMNICHANNEL INTO @NUNOTA
END


CLOSE cursor_ATUALIZAR_PEDIDO_OMNICHANNEL


DEALLOCATE cursor_ATUALIZAR_PEDIDO_OMNICHANNEL
END