














CREATE                                 PROCEDURE [sankhya].[AD_INS_MOV_BX_FIN_USE]    												 
AS
DECLARE
@P_NROUNICOUSE		INT,
@P_NUMBOR			INT,
@P_LOJA				INT,
@P_CLIENTE			INT,
@P_DATAPAGTO		DATETIME,
@P_DTFECHAMENTO		DATETIME,
@P_CODCTABCOINT		INT,
@P_NUFIN			INT


BEGIN

	DECLARE CURSOR_AD_INS_MOV_BX_FIN_USE CURSOR LOCAL FAST_FORWARD FOR   
		   SELECT TOP 200 C.CODIGO AS NROUNICOUSE
		        , F.CODIGO AS NUMBOR
				, C.LOJA
				, ISNULL(C.CLIENTE,0)
				, D.CODCTABCOINT
				, F.DATAPAGTO
				, FIN.NUFIN
			 FROM USE_CONTAREC (NOLOCK) F
		    INNER JOIN USE_VENDA  (NOLOCK) C ON F.VENDA = C.CODIGO AND F.LOJA = C.LOJA
			INNER JOIN AD_TGFLOJA  (NOLOCK) L ON C.LOJA = L.CODLOJA
			INNER JOIN TGFFIN FIN  (NOLOCK) ON  FIN.NUMBOR = F.CODIGO AND FIN.DHBAIXA IS NULL
			 LEFT JOIN AD_TGFCTAUSE  (NOLOCK) D ON F.CAIXAFINANCEIRO = D.CODIGO AND F.CAIXAFINANCEIROLOJA = D.LOJA
			 LEFT JOIN USE_CAIXA  (NOLOCK) A ON A.CONTAREC = F.CODIGO AND A.CONTARECLOJA = F.LOJA 
			WHERE F.DATAPAGTO >= CONVERT(DATE,'01/08/2024',103) -- Alinhado via teams com a Patricia essa data no dia 23/09/24 *** NAO ALTERAR ***
			  AND F.DATAPAGTO <= CONVERT(DATE,GETDATE()-1,103)
			  AND L.CODFRANQ = 1 
			  AND FIN.RECDESP = 1
			  --AND F.LOJA = 17
			  --AND C.DATAEXC IS NULL
			  AND FIN.CODTIPTIT <> 210 -- PIX A RECEBER, ALTERADO NO DIA 15/07 A PEDIDO DA EDILANE E LEILA
			  --AND F.VALORPAGTO > 0 -- ALTERADO NO DIA 21/08/23 PARA BUSCAR BAIXA COM O VALOR ZERADO - SOLICITACAO MELYSA
			  --AND F.FORMA <> 1  -- EXCLUIDO A BAIXA DO DINHEIRO CONF. SOLICITACAO CARLA 08/03/23 -- INSERIDO NOVAMENTE NA DATA 31/07/23 A PEDIDO DA CARLA -- EXCLUIDO A BAIXA DO DINHEIRO CONF. SOLICITACAO CARLA 20/12/23 -- INSERIDO NOVAMENTE NA DATA 25/01/24 A PEDIDO DA CARLA
			  AND CASE WHEN F.FORMA = 1  THEN (SELECT MIN(CODCTABCOINT) FROM AD_TGFCTAUSE (NOLOCK) WHERE TIPO = 'CX' AND LOJA = L.CODLOJA) -- DINHEIRO
					   WHEN F.FORMA = 5  THEN (SELECT MIN(CODCTABCOINT) FROM AD_TGFCTAUSE (NOLOCK) WHERE TIPO = 'AD' AND LOJA = L.CODLOJA) -- VALE PRESENTE
					   ELSE ISNULL(D.CODCTABCOINT,0) END <> 0
			  AND F.CODIGO NOT IN (SELECT NUMBOR FROM AD_TGFMIU (NOLOCK) WHERE TIPOMOVUSE = 'ERROBX' AND CODLOJAUSE = C.LOJA AND CODMOVUSE = C.CODIGO) 
		--	  AND FIN.NUFIN = 9813907
		      AND F.EXCLUIDOALTPLANO <> 1 -- DESCONSIDERAR TITULO ANTIGO, CONSIDERAR SOMENTE OS TITULOS APOS ALTERAÇÃO DE PLANO
			ORDER BY F.DATAPAGTO, F.LOJA
 
			OPEN CURSOR_AD_INS_MOV_BX_FIN_USE  
			FETCH NEXT FROM CURSOR_AD_INS_MOV_BX_FIN_USE INTO				@P_NROUNICOUSE, @P_NUMBOR,@P_LOJA,@P_CLIENTE,@P_CODCTABCOINT,@P_DATAPAGTO, @P_NUFIN
			
			WHILE @@FETCH_STATUS = 0  
			BEGIN  			

				BEGIN TRY	 

			       SELECT @P_DTFECHAMENTO = MAX(DTFECHAMENTO)
			         FROM AD_TGFFMBC (NOLOCK)
					WHERE CODCTABCOINT = @P_CODCTABCOINT

					IF @P_DATAPAGTO <= @P_DTFECHAMENTO
						BEGIN
							INSERT INTO AD_TGFMIU
								(CODMOVUSE,CODLOJAUSE,CODPARCUSE,TIPOMOVUSE,NUMBOR,LOGERRO,DATAUSE,NUFIN)
							VALUES
								(@P_NROUNICOUSE,@P_LOJA,@P_CLIENTE,'ERROBX',@P_NUMBOR,'Conta já conciliada na data',CONVERT(DATE,GETDATE(),103), @P_NUFIN)
							
							RETURN
						END        

					EXEC AD_INS_FIN_BXA_USE			@P_NROUNICOUSE, @P_NUMBOR 

				END TRY
				BEGIN CATCH

					INSERT INTO AD_TGFMIU
						(CODMOVUSE,CODLOJAUSE,CODPARCUSE,TIPOMOVUSE,NUMBOR,LOGERRO,DATAUSE,NUFIN)
					VALUES
						(@P_NROUNICOUSE,@P_LOJA,@P_CLIENTE,'ERROBX',@P_NUMBOR,ERROR_MESSAGE(),CONVERT(DATE,GETDATE(),103),@P_NUFIN)

				END CATCH

				FETCH NEXT FROM CURSOR_AD_INS_MOV_BX_FIN_USE INTO 		@P_NROUNICOUSE, @P_NUMBOR,@P_LOJA,@P_CLIENTE,@P_CODCTABCOINT,@P_DATAPAGTO, @P_NUFIN
			END  
  
			CLOSE CURSOR_AD_INS_MOV_BX_FIN_USE  
			DEALLOCATE CURSOR_AD_INS_MOV_BX_FIN_USE  
		
END;
