



CREATE                                                                                                                                              PROCEDURE [sankhya].[AD_INS_MOV_VDA_USE]    												 
AS
DECLARE
@P_NROUNICOUSE		INT,
@P_LOJA				INT,
@P_CLIENTE			INT,
@P_TIPO				VARCHAR(100),
@P_DATA				DATE,
@P_CPF				VARCHAR(20)

BEGIN

	DECLARE CURSOR_AD_INS_MOV_VDA_USE CURSOR LOCAL FAST_FORWARD FOR   
	SELECT TOP 30 M.CODMOVUSE,M.CODLOJAUSE
	  FROM AD_TGFMIU M (NOLOCK)
     INNER JOIN USE_VENDA (NOLOCK) V ON M.CODMOVUSE = V.CODIGO AND M.CODLOJAUSE = V.LOJA AND V.CHAVENFE IS NOT NULL
	 WHERE M.DATAUSE >= CONVERT(DATE,'01/01/2024',103)
	   --AND FORMAT(M.DATAUSE,'dd/MM/yyyy') <= FORMAT(GETDATE()-1,'dd/MM/yyyy')
	   AND M.TIPOMOVUSE = 'VDA'
	  -- AND M.CODLOJAUSE IN (70)
	   AND M.CODPARCSNK > 0
	   AND M.NUNOTASNK IS NULL
	   AND M.PROCESSADO IS NULL
	   AND ISNULL(M.NFEXCLUIDA,'N') <> 'S'
	 ORDER BY M.DATAUSE,M.CODLOJAUSE,M.CODMOVUSE
	   
  
			OPEN CURSOR_AD_INS_MOV_VDA_USE  
			FETCH NEXT FROM CURSOR_AD_INS_MOV_VDA_USE INTO				@P_NROUNICOUSE,@P_LOJA
			
			WHILE @@FETCH_STATUS = 0  
			BEGIN  

			

				BEGIN TRY	 
					EXEC AD_INS_CAB_VDA_USE			@P_NROUNICOUSE 
					UPDATE AD_TGFMIU SET PROCESSADO = 'S' WHERE CODMOVUSE = @P_NROUNICOUSE 
				END TRY
				BEGIN CATCH
					UPDATE AD_TGFMIU SET  PROCESSADO = 'S', LOGERRO = ERROR_MESSAGE() WHERE CODMOVUSE = @P_NROUNICOUSE
				END CATCH

				EXEC AD_INS_ITE_VDA_USE			@P_NROUNICOUSE

				EXEC AD_INS_DIN_VDA_USE			@P_NROUNICOUSE

				--EXEC AD_INS_FIN_VDA_USE			@P_NROUNICOUSE


				UPDATE AD_TGFMIU SET NUNOTASNK = (SELECT MAX(NUNOTA) FROM TGFCAB (NOLOCK) WHERE NUMCF = @P_NROUNICOUSE AND CODTIPOPER IN (3289,3290) AND CODEMP = (SELECT CASE WHEN CODEMP = 8 THEN 302 ELSE CODEMP END FROM AD_TGFLOJA (NOLOCK) WHERE CODLOJA = @P_LOJA))
				 WHERE CODMOVUSE = @P_NROUNICOUSE 

				/*SELECT @P_CPF = REPLACE(REPLACE(CPF,'.',''),'-','')
				  FROM USE_CLIENTE (NOLOCK)
				 WHERE CODIGO = @P_NROUNICOUSE */

				/*UPDATE AD_TGFMIU SET CODPARCSNK = (SELECT MIN(CODPARC) FROM TGFPAR (NOLOCK) WHERE CGC_CPF = @P_CPF)
				 WHERE CODMOVUSE = @P_NROUNICOUSE */




	
				FETCH NEXT FROM CURSOR_AD_INS_MOV_VDA_USE INTO 		@P_NROUNICOUSE,@P_LOJA
			END  
  
			CLOSE CURSOR_AD_INS_MOV_VDA_USE  
			DEALLOCATE CURSOR_AD_INS_MOV_VDA_USE  


		
END;
