
CREATE   PROCEDURE [sankhya].[AD_INS_CAB_CLI_USE] (   @P_NROUNICOUSE		    INT)										 
AS
DECLARE
	@P_DHTIPOPER			DATETIME,
	@P_DHTIPVENDA			DATETIME,
	@P_TIPMOV				VARCHAR(1),
	@P_CODPARC				INT,
	@P_NUNOTA				INT,
	@ERRMSG					VARCHAR(4000),
	@P_CPF_CLIENTE			VARCHAR(14),
	@P_DTNEG				DATE,
	@P_NUMNOTA				INT,
	@P_SERIENOTA			VARCHAR(3),
	@P_VLRNOTA				FLOAT,
	@P_CHAVENFE				VARCHAR(44),
	@P_CIF_FOB				VARCHAR(1),
	@P_STATUSNFE			VARCHAR(1),
	@P_NUMPROTOC			VARCHAR(15),
	@P_BASEICMS				FLOAT,
	@P_VLRICMS				FLOAT,
	@P_BASESUBSTIT			FLOAT,
	@P_VLRSUBST				FLOAT,
	@P_VLRSEG				FLOAT,
	@P_VLROUTROS			FLOAT,
	@P_BASEIPI				FLOAT,
	@P_VLRIPI				FLOAT,
	@P_VLRFRETE 			FLOAT,
	@P_BASEICMSFRETE 		FLOAT,
	@P_ICMSFRETE 			FLOAT,
	@P_VLRDESCTOTITEM 		FLOAT,									 
	@P_CODEMP				INT,										 
	@P_CODUSU				INT,
	@P_CODTIPOPER			INT,
	@P_CODTIPVENDA			INT,
	@P_CODCENCUS			INT,
	@P_CODNAT				INT,
	@P_MODELONF				INT,
	@P_CODPARCLOJA			INT,
	@P_VLRICMSDIFALDEST		FLOAT,
	@P_VLRICMSDIFALREM		FLOAT,
	@P_CODIGO				INT

BEGIN


	/*BUSCA DADOS USE*/
	SELECT @P_NROUNICOUSE = M.CODIGO -- BASE PARA O NUNOTA, CODIGO ÚNICO PARA IDENTIFICAR A VENDA
		 , @P_CPF_CLIENTE = REPLACE(REPLACE(REPLACE(P.CPF,'.',''),'-',''),'/','') -- CONSULTAR NA TGFPAR SE EXISTE 
		 , @P_DTNEG = M.DATEMI
		 , @P_NUMNOTA = M.NOTA
		 , @P_SERIENOTA = M.SERIENF
		 , @P_VLRNOTA = M.VALORTOTALNOTA
		 , @P_CHAVENFE = M.CHAVENFE
		 , @P_CIF_FOB = CASE WHEN M.TIPOFRETE = 9 THEN 'S' ELSE 'C' END
		 , @P_STATUSNFE = CASE WHEN M.STATUSNFE = 3 THEN 'A' END
		 , @P_NUMPROTOC = M.PROTOCOLOAUTO
		 , @P_BASEICMS = M.BASEICMS
		 , @P_VLRICMS = M.VALORICMS
		 , @P_BASESUBSTIT = M.BASEICMSSUBST
		 , @P_VLRSUBST = M.VALORICMSSUBST
		 , @P_VLRSEG = M.VALORSEGURO
		 , @P_VLROUTROS = M.VALOROUTRAS
		 , @P_BASEIPI = CASE WHEN M.VALORIPI > 0 THEN M.BASEICMS ELSE 0 END
		 , @P_VLRIPI = M.VALORIPI
		 , @P_VLRFRETE = ISNULL(M.VALORFRETE,M.TOTALFRETE)
		 , @P_BASEICMSFRETE = M.BASEICMSFRETE
		 , @P_ICMSFRETE = M.VALORICMSFRETE
		 , @P_VLRDESCTOTITEM = M.DESCONTOTALNOTA
		 , @P_CODEMP = L.CODEMP
		 , @P_CODUSU = 0
		 , @P_CODTIPOPER = C.CODTIPOPER 
		 , @P_CODTIPVENDA = 5
		 , @P_CODCENCUS = 0
		 , @P_CODNAT = 10010206
		 , @P_MODELONF = M.MODELONF 
		 , @P_CODPARCLOJA = L.CODPARC
	     , @P_VLRICMSDIFALDEST = M.VICMSUFDEST
	     , @P_VLRICMSDIFALREM = M.VICMSUFREMET
		 , @P_CODIGO = P.CODIGO
	  FROM AD_TGFLOJA (NOLOCK) L 
	 INNER JOIN USE_MOVIMENTOESTSAI (NOLOCK) M ON L.CODLOJA = M.LOJA AND M.STATUSNFE = 3 
	 INNER JOIN AD_TGFCFOUSE (NOLOCK) C ON C.CFOP = M.CFOP 
	 LEFT JOIN USE_CLIENTE (NOLOCK) P ON M.CLIENTE = P.CODIGO
	 WHERE /*L.ATIVO = 'S'  
	   AND*/ L.CODFRANQ = 1 -- LOJAS PROPRIAS
	   AND M.CODIGO = @P_NROUNICOUSE
	   AND M.DATACANCELNFE IS NULL
	   AND M.CHAVENFE IS NOT NULL
	   AND M.CODIGO NOT IN (SELECT ISNULL(C.NUMCF,0) 
							  FROM TGFCAB (NOLOCK) C 
							 INNER JOIN AD_TGFCFOUSE F ON C.CODTIPOPER = F.CODTIPOPER 
							 WHERE C.DTNEG = M.DATEMI 
							   AND C.CODEMP = L.CODEMP
							   AND C.TIPMOV <> 'V' )


    /*ATUALIZAR NATUREZA CASO A NOTA SEJA VENDA*/
	IF @P_CODTIPOPER IN (3289,3290)
   BEGIN 
     SET @P_CODNAT = 10010102
   END 


	/*BUSCA SE EXISTE O PARCEIRO*/
	SELECT @P_CODPARC = ISNULL(MIN(CODPARC),0)
      FROM TGFPAR (NOLOCK)
     WHERE ATIVO = 'S'
	   AND CGC_CPF = @P_CPF_CLIENTE 

	   	/*BUSCAR O CENTRO RESULTADO*/
	SELECT @P_CODCENCUS = ISNULL(EFDCODCENCUS,0)
	  FROM TGFEMP (NOLOCK)
	 WHERE CODEMP = @P_CODEMP


	 IF @P_CODPARC = 0
		/*INSERIR CLIENTE*/
		BEGIN
			EXEC SANKHYA.AD_INS_PAR_CLI_USE  @P_CODIGO, @P_CODPARCLOJA
		END
	
	/*BUSCA DADOS DA TOP*/
	SELECT @P_DHTIPOPER = MAX(DHALTER)
	     , @P_TIPMOV = TIPMOV
	  FROM TGFTOP  (NOLOCK)
	 WHERE CODTIPOPER = @P_CODTIPOPER
	 GROUP BY TIPMOV
	
	/*BUSCA DADOS DO TIPO DE NEGOCIACAO*/
	SELECT @P_DHTIPVENDA = MAX(DHALTER)
      FROM TGFTPV  (NOLOCK)
     WHERE CODTIPVENDA = @P_CODTIPVENDA
	
	/*BUSCA CODIGO DO PARCEIRO*/
	SELECT @P_CODPARC = MIN(CODPARC)
      FROM TGFPAR  (NOLOCK)
     WHERE ATIVO ='S'
	   AND CGC_CPF = @P_CPF_CLIENTE 

	UPDATE TGFPAR SET CLIENTE = 'S', FORNECEDOR = 'S' WHERE CODPARC = @P_CODPARC

	EXEC sankhya.STP_KEYGEN_TGFNUM 'TGFCAB', 1, 'TGFCAB', 'NUNOTA', 0, @P_NUNOTA OUT

		BEGIN
			/*INSERIR CABEÇALHO DA NOTA*/
			INSERT INTO TGFCAB (NUNOTA,CODEMP,CODCENCUS,NUMNOTA,SERIENOTA,DTNEG,DTFATUR,
								DTENTSAI,DTVAL,DTMOV,DTCONTAB,HRMOV,CODEMPNEGOC,
								CODPARC,CODCONTATO,RATEADO,CODVEICULO,CODTIPOPER,DHTIPOPER,
								TIPMOV,CODTIPVENDA,DHTIPVENDA,NUMCOTACAO,CODVEND,COMISSAO,
								CODMOEDA,CODOBSPADRAO,OBSERVACAO,VLRSEG,VLRICMSSEG,VLRDESTAQUE,
								VLRJURO,VLRVENDOR,VLROUTROS,VLREMB,VLRICMSEMB,VLRDESCSERV,IPIEMB,
								TIPIPIEMB,VLRDESCTOT,VLRDESCTOTITEM,VLRFRETE,ICMSFRETE,BASEICMSFRETE,
								TIPFRETE,CIF_FOB,VENCFRETE,VLRNOTA,VENCIPI,ORDEMCARGA,
								SEQCARGA,KMVEICULO,CODPARCTRANSP,QTDVOL,PENDENTE,BASEICMS,VLRICMS,
								BASEIPI,VLRIPI,ISSRETIDO,BASEISS,VLRISS,CODUSU,APROVADO,VLRIRF,
								IRFRETIDO,STATUSNOTA,COMGER,DTALTER,VOLUME,CODPARCDEST,
								VLRSUBST,BASESUBSTIT,CODPROJ,NUMCONTRATO,BASEINSS,VLRINSS,VLRREPREDTOT,
								PERCDESC,CODPARCREMETENTE,CODPARCCONSIGNATARIO,CODPARCREDESPACHO,LOCALCOLETA,
								LOCALENTREGA,VLRMERCADORIA,PESO,NOTASCF,CODMODDOC,CODNAT,CODMAQ,CODFUNC,
								NUMOS,NUMCF,VLRFRETECPL,TROCO,NROREDZ,VLRMOEDA,OCCN48,CODUSUINC,
								NUTRANSF,NURD8,CODSITE,TOTALCUSTOPROD,TOTALCUSTOSERV,CODCID,BASESUBSTSEMRED,
								CODMOTORISTA,NATUREZAOPERDES,SERIENFDES,MODELONFDES,CODUSUCOMPRADOR,
								DTPREVENT,NUNOTAPEDFRET,BASEIRF,ALIQIRF,PLACA,UFVEICULO,PESOBRUTO,
								HRENTSAI,ANTT,LACRES,DANFE,CHAVENFE,NUMERACAOVOLUMES,DTENVIOPMB,TIPNOTAPMB,
								NUMALEATORIO,NUMPROTOC,DHPROTOC,DTENVSUF,NULOTENFE,STATUSNFE,TPEMISNFE,
								DTADIAM,HRADIAM,CODDOCA,DIGITAL,TOTDISPDESC,BASEPIS,VLRPIS,BASEPISST,
								VLRPISST,BASECOFINS,VLRCOFINS,BASECOFINSST,VLRCOFINSST,VLRROYALT,NROCAIXA,
								NUMREGDPEC,DHREGDPEC,CODEMPFUNC,VLRINDENIZ,MARCA,TIPOPTAGJNFE,TPEMISNFSE,
								NULOTENFSE,NUMNFSE,STATUSNFSE,UFEMBARQ,LOCEMBARQ,TPLIGACAO,CODGRUPOTENSAO,
								TPASSINANTE,AGRUPBOL,NUREM,RETDATACRITICA,QTDBATIDAS,PERCPUREZA,PERCGERMIN,
								FRETEVLRBRUTO,FRETEVLRDESC,FRETEPERCDESC,FRETEVLRIMP,FRETEVLRJUR,FRETEVLRPAGO,
								CODVENDTEC,NUMPEDIDO,VLRINDENIZDIST,CODAGENDA,DTREF,FRETEVLRNEGOC,CODPRODPERMUTA,
								NROGAR,MD5PAF,CODMODDOCNOTA,CPFCNPJADQUIRENTE,NOMEADQUIRENTE,VLRSACADOLAR,
								NUMPEDIDO2,NUMCOO,ORDEMCARGAANT,TPAMBNFE,PRZMED,CODRESIDUO,DTREF2,
								VLRLIQITEMNFE,CLASCONS,NUMFORM,DTREF3,CODCC,PRODUETLOC,VLRSTEXTRANOTATOT,
								NUTRANEMP,SITESPECIALRESP,DTENTSAIINFO,EXIGEISSQN,REGESPTRIBUT,MOTNAORETERISSQN,
								DTREMRET,LIBCONF,NUCONFATUAL,STATUSXTRATEGIE,CODSAF,VLRFRETECALC,VLRJURODIST,
								NOTAEMPENHO,CODTPD,CODVTP,CANCELADO,PESOBRUTOMANUAL,PESOLIQUIMANUAL,NUPCA,
								INDPRESNFCE,M3,VLRTOTLIQITEMMOE,VLRDESCTOTITEMMOE,CHAVECTE,PRODPRED,TPEMISCTE,
								TPAMBCTE,LOTACAO,STATUSCTE,NUMALEATORIOCTE,NUMPROTOCCTE,DHPROTOCCTE,NULOTECTE,
								DTDECLARA,REBOQUE1,REBOQUE2,REBOQUE3,SITUACAOCTE,CTELOTACAO,CODVEITRACAO,
								CODOBRA,CODART,IDIPROC,VIATRANSP,TIPPROCIMP,CNPJADQUIRENTE,UFADQUIRENTE,
								DHEMISSEPEC,NUNOTASUB,CHAVENFSE,MODENTREGA,VLRICMSDIFALDEST,VLRICMSDIFALREM,
								CIOT,VLRFRETETOTAL,CODPARCTRANSPFINAL,VLRICMSFCP,FUSOEMISSEPEC,VLRDESCRAT,
								CHAVENFEREF,SEQCONFIRMA,CODCONTATOENTREGA,CODCIDORIGEM,CODCIDDESTINO,CODCIDENTREGA,
								CODUFORIGEM,CODUFDESTINO,CODUFENTREGA,CLASSIFICMS,NUFOP,CODRASTREAMENTOECT,NUODP,
								NUPEDFRETE,CODCIDPREST,FORMPGTCTE,PERCDESCFOB,TPAMBNFSE,TERMACORDNOTA,VLRDESCQTD,
								VLRICMSFCPINT,VLRSTFCPINT,VLRSTFCPINTANT,CTEGLOBAL,VLRCARGAAVERB,CODCIDINICTE,CODCIDFIMCTE,
								NUCFR,VLRPRESTAFRMM,VLRAFRMM,IDNAVIO,IRINNAVIO,DIRECAOVIAG,IDBALSA01,
								IDBALSA02,IDBALSA03,NFEDEVRECUSA,AGRUPFINNOTA,CONFIRMNOTAFAT,PERMALTERCENTRAL,CODGUF,
								VLRREPREDTOTSEMDESC,FINALIZADOFOX,NUMCUPOMECONECT,DTEXTEMPK280,TIMNUFINORIG,TIMCONTRATOVENDA,TIMORIGEM,
								TIMCONTRATOLTV,TIMNUNOTAMOD,LATITUDE,LONGITUDE,CODPARCDESCARGAMDFE,CODDOCARRECAD,NUMDOCARRECAD,
								PREMIACAOESTADUAL,NFSEID,CODPARCDEPO,CODCHECKOUT,
								DISDESAUTIMPEMB,VLRFETHAB,IDDESCPARCERIA,VLRDESCPARCERIA,CLIENTEIDPARCERIA,IDPONTUACAOPARCERIA,BASEICMSAT,VLRICMSAT,
								AD_DTNEGORIG)
						VALUES (@P_NUNOTA,@P_CODEMP,@P_CODCENCUS,@P_NUMNOTA,@P_SERIENOTA,@P_DTNEG,@P_DTNEG,
								@P_DTNEG,NULL,GETDATE(),NULL,FORMAT(GETDATE(),'hhmmss'),@P_CODEMP,
								ISNULL(@P_CODPARC,135225),NULL,'N',0,@P_CODTIPOPER,@P_DHTIPOPER,
								@P_TIPMOV,@P_CODTIPVENDA,@P_DHTIPVENDA,NULL,0,0,
								0,0,NULL,@P_VLRSEG,0,0,
								0,0,@P_VLROUTROS,0,0,0,0,
								'N',0,@P_VLRDESCTOTITEM,@P_VLRFRETE,@P_ICMSFRETE,@P_BASEICMSFRETE,
								'N',@P_CIF_FOB,NULL,@P_VLRNOTA,NULL,0,
								NULL,NULL,0,1,'N',@P_BASEICMS,@P_VLRICMS,
								@P_BASEIPI,@P_VLRIPI,'N',0,0,@P_CODUSU,'N',0,
								'S','L',NULL,GETDATE(),NULL,0,
								@P_VLRSUBST,@P_BASESUBSTIT,0,0,0,0,0,
								0,0,0,0,NULL,
								NULL,NULL,0,NULL,1,@P_CODNAT,NULL,NULL,
								NULL,@P_NROUNICOUSE,0,0,0,0,NULL,@P_CODUSU,
								0,NULL,NULL,0,0,0,0,
								0,NULL,NULL,NULL,0,
								NULL,NULL,0,0,NULL,NULL,0,
								GETDATE(),NULL,NULL,NULL,@P_CHAVENFE,NULL,NULL,NULL,
								NULL,@P_NUMPROTOC,NULL,NULL,NULL,@P_STATUSNFE,NULL,
								NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
								NULL,NULL,NULL,NULL,NULL,NULL,NULL,
								NULL,NULL,NULL,0,NULL,NULL,NULL,
								NULL,NULL,NULL,NULL,NULL,NULL,NULL,
								NULL,'N',NULL,NULL,NULL,NULL,NULL,
								NULL,NULL,NULL,NULL,NULL,NULL,
								NULL,NULL,NULL,NULL,NULL,NULL,NULL,
								NULL,NULL,NULL,NULL,NULL,NULL,
								NULL,NULL,NULL,NULL,NULL,NULL,NULL,
								NULL,NULL,NULL,NULL,NULL,'N',0,
								NULL,NULL,NULL,NULL,NULL,NULL,
								NULL,NULL,NULL,NULL,NULL,NULL,NULL,
								NULL,NULL,NULL,NULL,NULL,NULL,NULL,
								0,0,0,0,NULL,NULL,NULL,
								NULL,NULL,NULL,NULL,NULL,NULL,NULL,
								NULL,NULL,NULL,NULL,NULL,NULL,NULL,
								NULL,NULL,NULL,NULL,NULL,NULL,NULL,
								NULL,NULL,NULL,NULL,@P_VLRICMSDIFALDEST,@P_VLRICMSDIFALREM,
								NULL,NULL,NULL,NULL,NULL,0,
								NULL,NULL,NULL,0,0,0,
								0,2,0,'R',NULL,NULL,NULL,
								NULL,NULL,NULL,NULL,NULL,NULL,NULL,
								NULL,NULL,NULL,NULL,NULL,NULL,NULL,
								NULL,NULL,NULL,NULL,NULL,NULL,NULL,
								NULL,NULL,NULL,NULL,NULL,NULL,NULL,
								0,NULL,NULL,NULL,NULL,NULL,NULL,
								NULL,NULL,NULL,NULL,NULL,NULL,NULL,
								NULL,NULL,NULL,NULL,NULL,
								NULL,NULL,NULL,NULL,NULL,NULL,NULL,
								@P_DTNEG)
		END

		
END;
